---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jenkins-policy
  namespace: wds-test
spec:
  podSelector:
    matchLabels:
      app: jenkins
  ingress:
  - ports:
    - protocol: TCP
      port: 8080

